### ISSUE TITLE
Required and optional fields

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/esl#12]
ESL class fields

| Field | Type | Required | Notes |
| --- | :-: | --: | --: |
| Address | Text | Yes |  |
| Phone Number | Text | Yes |  |
| Email | Text | No |  |
| Level | Enum | Yes | Values: (Beginner, Intermediate, Advanced) |
| allowsWalkins | Boolean | Yes |  |
| isBusinessFocus | Boolean | Yes |  |
| Cost | Numeric | Yes |  |
| Day | Text | No |  |
| Time of Day | Text | No |  |
| Notes | Text | No |  |

**Comment by DavidEBest** [comment]
The Level, isBusinessFocus, and Cost fields are not in our current data. Who should we reach out to for this info?

**Comment by dwcaraway** [comment]
I'll contact melissa b

**Comment by dwcaraway** [comment]
Closing this out, think we have all the information displayed that we have
