### ISSUE TITLE
Simple Feedback

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/esl#17]
A user is provided with an icon set (sad face, neutral face, smiley face) on page at all times. Most recent feedback is shown as selected. When a new feedback is given, an optional text box is available to submit questions or comments.

**Comment by DavidEBest** [comment]
Should this be included as part of the application or should it rely on Wordpress functionality in WelcomeDayton? Our contact from that organization did not seem thrilled with having another system/site to check for feedback.

**Comment by dwcaraway** [comment]
You ask a fair question. I think we only need to worry about user feedback while we (Code for Dayton) are actively working on the site or have it privately hosted. I'm interested in the [Uservoice widget](http://feedback.uservoice.com/knowledgebase/articles/170432-setup-the-uservoice-widget), since we already use uservoice for our project backlog.

Once it is deployed (e.g. on WelcomeDayton), any feedback should be integrated into their existing system. That said, I didn't see a ready feedback mechanism on the welcomedayton.org website other than standard email or phone call.

**Comment by DavidEBest** [comment]
Added in commit #36.
