### ISSUE TITLE
Build a filter list

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/esl#19]
Add a 'control panel' to the page that allows the users to show/hide map markers (and maybe items in the list control).

Filters should include childcare, day of week, time of day, walk ins allowed, cost, etc.

**Comment by DavidEBest** [comment]
Should this be in the MVP?

**Comment by raudabaugh** [comment]
I just set it to MVP. From what I remember we talked about filters being in the MVP in the initial meeting.

**Comment by DavidEBest** [comment]
Should be completed with latest merge.
