### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ianebaldwin** [codefordayton/esl#20]
Here is a list of icons we need to pull from Font Awesome (http://fortawesome.github.io/Font-Awesome/).

<strong>Class Info</strong>
- Map Marker -- fa-map-marker `(&#xf041;)`
- Phone -- fa-phone `(&#xf095;)`
- Email -- fa-envelope `(&#xf0e0;)`
- Beginner 1, Circle Int. 2 Circles, Adv. 3 Circles -- fa-circle `(&#xf111;)`
- Walk-Ins -- fa-arrow-circle-o-right `(&#xf18e;)`
- Business -- fa-briefcase `(&#xf0b1;)`
- Fee (if any) -- `fa-usd (&#xf155;)`
- Calendar -- fa-calendar `(&#xf073;)`
- Time -- fa-clock-o `(&#xf017;)`
- Notes -- fa-book `(&#xf02d;)`

If you can think of anymore we might need please add to this list.

**Comment by DavidEBest** [comment]
Fixed in commit #39.
