### ISSUE TITLE
Update class listing

### ISSUE THREAD

**Issue by dwcaraway** [codefordayton/esl#22]
Add new listing

Redeemer Orthodox Presbyterian
22 S. Fairfield
Beavercreek, Ohio
937-426-9965
Thursday 6:45-8:45
Beginner, Intermediate, and Advanced
Childcare is available

**Comment by DavidEBest** [comment]
Added and merged. New entry is live now.

**Comment by dwcaraway** [comment]
sweet! thx

On Feb 14, 2014, at 6:34 AM, David Best notifications@github.com wrote:

Added and merged. New entry is live now.

## 

Reply to this email directly or view it on
GitHubhttps://github.com/codefordayton/esl/issues/22#issuecomment-35076205
.
