### ISSUE TITLE
Commit access?

### ISSUE THREAD

**Issue by DavidEBest** [codefordayton/esl#3]
Maybe I'm just showing my inexperience with github, but should I be able to push to this repo? If not, what would be the appropriate way to update - fork and then pull request?

I've created a basic index.html file that uses the Google Maps api. Not much, but it is a start.

**Comment by dwcaraway** [comment]
Dave++, gave you owner rights, you can do anything that I can. Use direct commits for simple stuff. If the code is complex and needs review, pull request it.

And awesome!

Closing...
